spring.application.name=shop

spring.datasource.url= ${MYSQL_URL}
spring.datasource.username=${MYSQL_USER}
spring.datasource.password=${MYSQL_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.web.resources.add-mappings=false

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

spring.config.import=classpath:security.properties